### ISSUE TITLE
Failed: Malformed packet

### ISSUE THREAD

**Issue by felixge** [insomniacslk/dublin-traceroute#27] opened 2017-11-28 00:34 UTC
Thanks for working on this project!

I installed via `brew install 'https://raw.githubusercontent.com/insomniacslk/dublin-traceroute/master/homebrew/dublin-traceroute.rb'` and am seeing the following error when trying it out:

```
$ sudo dublin-traceroute google.com
WARNING: you are running this program as root. Consider setting the CAP_NET_RAW
         capability and running as non-root user as a more secure alternative.
Starting dublin-traceroute
Traceroute from 0.0.0.0:12345 to google.com:33434~33453 (probing 20 paths, min TTL is 1, max TTL is 30, delay is 10 ms)
Failed: Malformed packet
```

Let me know if I should provide more information.

**Comment by insomniacslk** [comment] 2017-11-28 23:07
Hi @felixge , what version of dublin-traceroute are you using? You can check it with `dublin-traceroute --version`. Before we dig into this issue can you check if this happens with HEAD?

Thanks

**Comment by felixge** [comment] 2017-11-28 23:33
```
$ dublin-traceroute --version
Dublin Traceroute 0.4.2
```

Is building HEAD supported via homebrew?

Thanks for the fast reply!

**Comment by insomniacslk** [comment] 2017-11-29 09:54
Yes, you can add `--HEAD` to the `brew install` command

**Comment by insomniacslk** [comment] 2017-11-29 09:56
Also what's your OSX version?

**Comment by insomniacslk** [comment] 2017-11-29 13:50
Just tried myself on a macOS High Sierra using `--HEAD` and I can't reproduce. Will look for other macOS versions too. Meanwhile, if the issue doesn't disappear on your side, can you tcpdump the traffic with something like this?

On one terminal:
```bash
sudo dublin-traceroute 8.8.4.4 -n 1 -s 33434 -T15
```

and on another terminal:
```bash
sudo tcpdump -s0 -nlv -i any '(dst host 8.8.4.4 and udp port 33434) or icmp'
```

**Comment by insomniacslk** [comment] 2017-11-29 15:32
Thanks!

**Comment by felixge** [comment] 2017-11-29 16:59
I'm behind the same VPN again and can't reproduce the issue. Sorry for the trouble. I'll reopen with more details if I see it again.

**Comment by insomniacslk** [comment] 2017-11-29 17:15
no worries :) happy this works for you now!

**Comment by jkldgoefgkljefogeg** [comment] 2018-02-04 13:42
I frequently get `Failed: Malformed packet`. No VPN involved.

**Comment by insomniacslk** [comment] 2018-02-04 14:09
hi @jkldgoefgkljefogeg , happy to help but I need some more information. What's your platform? Are you using a packaged version or from git? Any other information you can provide will help troubleshooting

**Comment by jkldgoefgkljefogeg** [comment] 2018-02-04 14:57
Debian GNU/Linux 9.3 (stretch)
Dublin Traceroute 0.4.2 (installed from debian deb)

Running the same traceroute sometimes it fails with `Failed: Malformed packet`. I will try to get a pcap next time it happens.

**Comment by insomniacslk** [comment] 2018-02-04 16:55
Thanks, the pcap would help a lot

**Comment by infinity0** [comment] 2018-03-29 11:04
This happens about 1/2 of the time when I traceroute google.com and roughly 3/4 of the time when I traceroute 8.8.8.8. Do you want the pcap in "pcap" or "pcap-ng" format? And do you have a GPG key I can encrypt the file to, b/c I don't want to post that sort of stuff publicly.

**Comment by infinity0** [comment] 2018-03-29 11:30
Perhaps the program shouldn't fail-hard on these malformed packets? The trace seems to go alright otherwise, the malformed packet could just be represented as [malformed packet] in the trace output.

**Comment by insomniacslk** [comment] 2018-04-03 07:44
can you attach a pcap file of a failed traceroute? If I can't reproduce it's hard to understand what's going on

**Comment by guigui80** [comment] 2018-04-06 08:46
Hello,

I have the same each time when I run dublintraceroute. I have tested dublintraceroute from deb 0.4.2 on debian:

`WARNING: you are running this program as root. Consider setting the CAP_NET_RAW
         capability and running as non-root user as a more secure alternative.
Starting dublin-traceroute
Traceroute from 0.0.0.0:12345 to 8.8.8.8:33434~33453 (probing 20 paths, min TTL is 1, max TTL is 30, delay is 10 ms)
Failed: Malformed packet
root@breaking:~# dublin-traceroute -v
WARNING: you are running this program as root. Consider setting the CAP_NET_RAW
         capability and running as non-root user as a more secure alternative.
Dublin Traceroute 0.4.2`

And I have tested too with python-dublin-traceroute from the git repo:
 `
/usr/local/lib# find -iname "dublin*"
./python2.7/dist-packages/dublintraceroute-0.4.2-py2.7-linux-x86_64.egg

python -m dublintraceroute trace 8.8.8.8
Traceroute to 8.8.8.8
  Source port: 12345, destination port: 33434, num paths: 20, min TTL: 1, max TTL: 30, delay: 10, broken NAT: False
terminate called after throwing an instance of 'Tins::malformed_packet'
  what():  Malformed packet
Aborted
`
A related post maybe it can help you on this issue:
https://github.com/mfontanini/libtins/issues/269

**Comment by insomniacslk** [comment] 2018-04-06 14:06
I was able to semi-consistently reproduce on a VPS, I'll have a look at this on the weekend. Ideally, improving the error message to know what exactly went wrong in decoding the packet is already a good help (and also log errors but not breaking on them)

**Comment by insomniacslk** [comment] 2018-04-07 17:47
Found the issue - it fails because of ICMP echo requests coming to the host, and the code doesn't check if the IP-in-ICMP serialization succeeded.

@guigui80 @infinity0 @jkldgoefgkljefogeg @felixge can you please check that the latest commit (https://github.com/insomniacslk/dublin-traceroute/commit/d2c3549ce315aeb5823c042d915e9e4c5bdd80ba) fixes this for you?

**Comment by guigui80** [comment] 2018-04-08 09:48
It  works for me now. I have run several time dublin-traceroute and no error has appeared.

**Comment by insomniacslk** [comment] 2018-04-08 10:24
awesome :) I will wait for some more feedback before closing this issue

**Comment by insomniacslk** [comment] 2018-04-11 19:41
I assume this is fixed. Closing

**Closed by insomniacslk** 2018-04-11 19:41 UTC
