### ISSUE TITLE
Segmentation fault at a hardened Gentoo Linux

### ISSUE THREAD

**Issue by toralf** [insomniacslk/dublin-traceroute#3] opened 2015-11-25 15:54 UTC
I got:
...
read(4, ".0.1 valtrex.1.p2l.info\n127.0.0."..., 4096) = 4096
read(4, "www.shopping-artikel.de\n127.0.0."..., 4096) = 4096
read(4, "Cole, William Jones, Brian Small"..., 4096) = 1585
read(4, "", 4096)                       = 0
close(4)                                = 0
munmap(0x384b17a1000, 4096)             = 0
socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 4
connect(4, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
poll([{fd=4, events=POLLOUT}], 1, 0)    = 1 ([{fd=4, revents=POLLOUT}])
sendto(4, "\345E\1\0\0\1\0\0\0\0\0\0\003163\003251\003239\003213\7in-"..., 46, MSG_NOSIGNAL, NULL, 0) = 46
poll([{fd=4, events=POLLIN}], 1, 5000)  = 1 ([{fd=4, revents=POLLIN}])
ioctl(4, FIONREAD, [89])                = 0
recvfrom(4, "\345E\201\200\0\1\0\1\0\0\0\0\003163\003251\003239\003213\7in-"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, [16]) = 89
close(4)                                = 0
setsockopt(3, SOL_PACKET, PACKET_RX_RING, {block_size=0, block_nr=0, frame_size=0, frame_nr=0}, 16) = -1 EINVAL (Invalid argument)
munmap(0x384af52b000, 2097152)          = 0
close(3)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x3e0} ---
+++ killed by SIGSEGV +++
Segmentation fault

FWIW:
# wc /etc/hosts
 11983  25536 362033 /etc/hosts

**Comment by insomniacslk** [comment] 2016-01-09 00:59
Hi @toralf , I cannot reproduce the bug with a large /etc/hosts ( 21212  42427 530246 hosts ). Can you please give more information?

Aside that, from the output of your strace it seems to be more an issue with a system library or a dependency than a bug in dublin-traceroute. In any case I'll be happy to work on it as soon as I can reproduce it.

**Comment by insomniacslk** [comment] 2016-01-09 01:09
@toralf despite this bug is apparently unrelated to the size of /etc/hosts, it also appears that you have some garbage in your /etc/hosts (see the third read() syscall)

**Comment by insomniacslk** [comment] 2016-01-15 22:45
Resolving since it cannot be reproduced and there's no follow-up

**Closed by insomniacslk** 2016-01-15 22:45 UTC
Labels: question
